spring.application.name=hostelfeedback1
spring.datasource.url=jdbc:mysql://localhost:3306/hostel_feedback
spring.datasource.username=root
spring.datasource.password=Achar@4691
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update



